version: '2'
services:
  tomcat:
    image: tomcat:9.0
    working_dir: /usr/local/tomcat
    ports:
      - 8080:8080
    # links:
    #   - db
    # depends_on:
    #   - db
    volumes:
      - ./webapp:/usr/local/tomcat/webapps
  node:
    image: node:9.4
    working_dir: /root
    command: bash -c "npm install && npm run prod"
    volumes:
      - ./package.json:/root/package.json
      - ./package-lock.json:/root/package-lock.json
      - ./gulpfile.js:/root/gulpfile.js:ro
      - ./views:/root/views:ro
      - ./webapp:/root/webapp
